require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AccountingsController do

  def mock_accounting(stubs={})
    @mock_accounting ||= mock_model(Accounting, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all accountings as @accountings" do
      Accounting.stub(:all) { [mock_accounting] }
      get :index
      assigns(:accountings).should eq([mock_accounting])
    end
  end

  describe "GET show" do
    it "assigns the requested accounting as @accounting" do
      Accounting.stub(:find).with("37") { mock_accounting }
      get :show, :id => "37"
      assigns(:accounting).should be(mock_accounting)
    end
  end

  describe "GET new" do
    it "assigns a new accounting as @accounting" do
      Accounting.stub(:new) { mock_accounting }
      get :new
      assigns(:accounting).should be(mock_accounting)
    end
  end

  describe "GET edit" do
    it "assigns the requested accounting as @accounting" do
      Accounting.stub(:find).with("37") { mock_accounting }
      get :edit, :id => "37"
      assigns(:accounting).should be(mock_accounting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created accounting as @accounting" do
        Accounting.stub(:new).with({'these' => 'params'}) { mock_accounting(:save => true) }
        post :create, :accounting => {'these' => 'params'}
        assigns(:accounting).should be(mock_accounting)
      end

      it "redirects to the created accounting" do
        Accounting.stub(:new) { mock_accounting(:save => true) }
        post :create, :accounting => {}
        response.should redirect_to(accounting_url(mock_accounting))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved accounting as @accounting" do
        Accounting.stub(:new).with({'these' => 'params'}) { mock_accounting(:save => false) }
        post :create, :accounting => {'these' => 'params'}
        assigns(:accounting).should be(mock_accounting)
      end

      it "re-renders the 'new' template" do
        Accounting.stub(:new) { mock_accounting(:save => false) }
        post :create, :accounting => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested accounting" do
        Accounting.stub(:find).with("37") { mock_accounting }
        mock_accounting.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :accounting => {'these' => 'params'}
      end

      it "assigns the requested accounting as @accounting" do
        Accounting.stub(:find) { mock_accounting(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:accounting).should be(mock_accounting)
      end

      it "redirects to the accounting" do
        Accounting.stub(:find) { mock_accounting(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(accounting_url(mock_accounting))
      end
    end

    describe "with invalid params" do
      it "assigns the accounting as @accounting" do
        Accounting.stub(:find) { mock_accounting(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:accounting).should be(mock_accounting)
      end

      it "re-renders the 'edit' template" do
        Accounting.stub(:find) { mock_accounting(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested accounting" do
      Accounting.stub(:find).with("37") { mock_accounting }
      mock_accounting.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the accountings list" do
      Accounting.stub(:find) { mock_accounting }
      delete :destroy, :id => "1"
      response.should redirect_to(accountings_url)
    end
  end

end
