require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProjectMilestonesController do

  def mock_project_milestone(stubs={})
    @mock_project_milestone ||= mock_model(ProjectMilestone, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all project_milestones as @project_milestones" do
      ProjectMilestone.stub(:all) { [mock_project_milestone] }
      get :index
      assigns(:project_milestones).should eq([mock_project_milestone])
    end
  end

  describe "GET show" do
    it "assigns the requested project_milestone as @project_milestone" do
      ProjectMilestone.stub(:find).with("37") { mock_project_milestone }
      get :show, :id => "37"
      assigns(:project_milestone).should be(mock_project_milestone)
    end
  end

  describe "GET new" do
    it "assigns a new project_milestone as @project_milestone" do
      ProjectMilestone.stub(:new) { mock_project_milestone }
      get :new
      assigns(:project_milestone).should be(mock_project_milestone)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_milestone as @project_milestone" do
      ProjectMilestone.stub(:find).with("37") { mock_project_milestone }
      get :edit, :id => "37"
      assigns(:project_milestone).should be(mock_project_milestone)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created project_milestone as @project_milestone" do
        ProjectMilestone.stub(:new).with({'these' => 'params'}) { mock_project_milestone(:save => true) }
        post :create, :project_milestone => {'these' => 'params'}
        assigns(:project_milestone).should be(mock_project_milestone)
      end

      it "redirects to the created project_milestone" do
        ProjectMilestone.stub(:new) { mock_project_milestone(:save => true) }
        post :create, :project_milestone => {}
        response.should redirect_to(project_milestone_url(mock_project_milestone))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_milestone as @project_milestone" do
        ProjectMilestone.stub(:new).with({'these' => 'params'}) { mock_project_milestone(:save => false) }
        post :create, :project_milestone => {'these' => 'params'}
        assigns(:project_milestone).should be(mock_project_milestone)
      end

      it "re-renders the 'new' template" do
        ProjectMilestone.stub(:new) { mock_project_milestone(:save => false) }
        post :create, :project_milestone => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested project_milestone" do
        ProjectMilestone.stub(:find).with("37") { mock_project_milestone }
        mock_project_milestone.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :project_milestone => {'these' => 'params'}
      end

      it "assigns the requested project_milestone as @project_milestone" do
        ProjectMilestone.stub(:find) { mock_project_milestone(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:project_milestone).should be(mock_project_milestone)
      end

      it "redirects to the project_milestone" do
        ProjectMilestone.stub(:find) { mock_project_milestone(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(project_milestone_url(mock_project_milestone))
      end
    end

    describe "with invalid params" do
      it "assigns the project_milestone as @project_milestone" do
        ProjectMilestone.stub(:find) { mock_project_milestone(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:project_milestone).should be(mock_project_milestone)
      end

      it "re-renders the 'edit' template" do
        ProjectMilestone.stub(:find) { mock_project_milestone(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_milestone" do
      ProjectMilestone.stub(:find).with("37") { mock_project_milestone }
      mock_project_milestone.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the project_milestones list" do
      ProjectMilestone.stub(:find) { mock_project_milestone }
      delete :destroy, :id => "1"
      response.should redirect_to(project_milestones_url)
    end
  end

end
